Conditonally call login_with_refresh_token
fylein/fyle-integrations-app pull request #810
Opened 2024-05-20 08:15 UTC by anishfyle

2024-05-21 07:32 UTC, DhaaraniCIT commented on src/app/auth/login/login.component.ts
> +          if (this.exposeApps.fyle.QBO) {
this is for fyle alone, what about co

2024-05-21 07:33 UTC, DhaaraniCIT requested changes

2024-05-21 07:33 UTC, DhaaraniCIT commented on src/app/auth/login/login.component.ts
> +          if (this.exposeApps.fyle.QBO) {
this is for fyle alone, what about co

2024-05-22 10:11 UTC, DhaaraniCIT requested changes

2024-05-22 10:11 UTC, DhaaraniCIT commented on src/app/auth/login/login.component.ts
> +        if (this.exposeApps.fyle.SAGE300 && this.exposeApps.co.SAGE300) {
in co sage300 will be hidden, that time this will not happen for Fyle as well, can you re-phase it, like the one in landing.ts `exposeAppConfig[brandingConfig.brandId][brandingConfig.envId]`

2024-05-22 10:11 UTC, DhaaraniCIT commented on src/app/auth/login/login.component.ts
> +        if (this.exposeApps.fyle.BUSINESS_CENTRAL && this.exposeApps.co.BUSINESS_CENTRAL) {
same as above

2024-05-22 10:11 UTC, DhaaraniCIT commented on src/app/auth/login/login.component.ts
> +          if (this.exposeApps.fyle.QBO && this.exposeApps.co.QBO) {
same as above

2024-05-22 16:06 UTC, ashwin1111 approved these changes

2024-05-23 09:25 UTC, merged