Unit Test: QBO Components
fylein/fyle-integrations-app pull request #925
Opened 2024-08-22 10:12 UTC by anishfyle

2024-08-29 05:48 UTC, DhaaraniCIT commented on src/app/integrations/qbo/qbo.component.spec.ts
> +  const mockUser: MinimalUser = {
can create fixture and call the values, so the file will be clean

2024-09-02 09:40 UTC, ashwin1111 requested changes

2024-09-02 09:40 UTC, ashwin1111 commented on src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-landing/qbo-onboarding-landing.component.spec.ts
> +});
cover 100% of lines

2024-09-02 09:40 UTC, ashwin1111 commented on src/app/integrations/qbo/qbo-shared/qbo-employee-settings/qbo-employee-settings.component.spec.ts
> +  }));
need to cover all lines and cases

2024-09-02 09:40 UTC, ashwin1111 commented on src/app/integrations/qbo/qbo.fixture.ts
> +    onboarding_state: QBOOnboardingState.CONNECTION
provide complete data with all keys

2024-09-17 17:03 UTC, ashwin1111 approved these changes

2024-09-19 03:31 UTC, merged